import { env } from './src/config/env.js';
console.log('✅ Env loaded');
import authRoutes from './src/routes/auth.routes.js';
console.log('✅ Auth routes loaded');
import categoryRoutes from './src/routes/category.routes.js';
console.log('✅ Category routes loaded');
import productRoutes from './src/routes/product.routes.js';
console.log('✅ Product routes loaded');
import orderRoutes from './src/routes/order.routes.js';
console.log('✅ Order routes loaded');
import invoiceRoutes from './src/routes/invoice.routes.js';
console.log('✅ Invoice routes loaded');
import paymentRoutes from './src/routes/payment.routes.js';
console.log('✅ Payment routes loaded');
import creditRoutes from './src/routes/credits.routes.js';
console.log('✅ Credit routes loaded');
import packingListRoutes from './src/routes/packing-list.routes.js';
console.log('✅ Packing list routes loaded');
import notificationRoutes from './src/routes/notification.routes.js';
console.log('✅ Notification routes loaded');
import reportRoutes from './src/routes/report.routes.js';
console.log('✅ Report routes loaded');
import customerRoutes from './src/routes/customer.routes.js';
console.log('✅ Customer routes loaded');
import auditRoutes from './src/routes/audit.routes.js';
console.log('✅ Audit routes loaded');
import adminRoutes from './src/routes/admin.routes.js';
console.log('✅ Admin routes loaded');
import uploadRoutes from './src/routes/upload.routes.js';
console.log('✅ Upload routes loaded');
import { schedulerService } from './src/services/scheduler.service.js';
console.log('✅ Scheduler service loaded');
console.log('🎉 All imports successful');
